apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service
  labels:
    app: simple-time-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-time-service
  template:
    metadata:
      labels:
        app: simple-time-service
    spec:
      containers:
        - name: simple-time-service
          image: ""  # the image name will take it automatically from the kubernetes-deployment.yaml pipeline 
          ports:
            - containerPort: 8085
          securityContext:
            runAsUser: 1942               
            runAsGroup: 1942              # Use the non-root group ID
            readOnlyRootFilesystem: true   # Enforce a read-only filesystem
            allowPrivilegeEscalation: false # Prevent privilege escalation
          resources:
            requests:
              cpu: "100m"                  # Request minimal CPU
              memory: "100Mi"               # Request minimal memory
            limits:
              cpu: "500m"                  # Limit CPU usage
              memory: "200Mi"              # Limit memory usage
