apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
  labels:
    app: simple-time-service
spec:
  selector:
    app: simple-time-service                # Match the deployment label
  ports:
    - protocol: TCP
      port: 8085                    
      targetPort: 8085            
  type: LoadBalancer               # Expose the service externally (if using cloud provider)
